import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 bg-gray-100 border-b flex gap-4">
          <Link href="/">Inicio</Link>
          <Link href="/productos">Productos</Link>
          <Link href="/about">Nosotros</Link>
          <Link href="/contacto">Contacto</Link>
          <Link href="/legal/terminos">Términos</Link>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
